[functions]
#Hookies since im too lazy to make another toml file.. :)
0x829690D8 = {name = "rex_render_CCalGraphicsRenderer_Create_829690D8"}
0x8296A838 = {name = "rex_render_CCalVideoRenderer_Close_8296A838"}
0x8296A940 = {name = "rex_render_CCalVideoRenderer_SetMediaInfo_8296A940"}
0x8296AB38 = {name = "rex_render_CCalVideoRenderer_Render_8296AB38"}
0x8296AF30 = {name = "rex_render_CCalVideoRenderer_InitializeShaders_8296AF30"}
0x8296A748 = {name = "rex_render_CCalVideoRenderer_InitializeVertices_8296A748"}
0x8265A2A8 = {name = "rex_render_D3DDevice_Clear_8265A2A8"}
0x82657F08 = {name = "rex_render_D3DDevice_SetScissorRect_82657F08"}
0x82658000 = {name = "rex_render_IDirect3DDevice9_SetViewport_82658000"}
0x8266FBB0 = {name = "rex_render_IDirect3DDevice9_Swap_8266FBB0"}
0x826703E0 = {name = "rex_render_D3DDevice_Present_826703E0"}

#CTX.CTR.U32
0x826878C0 = {}
0x825F3008 = {}
0x82A78878 = {}
0x82AB5234 = {}
0x82ABB414 = {}
0x82915e88 = {}
0x828d0040 = {}
0x82688540 = {}
0x826e4110 = {}
0x82547290 = {}
0x8268e990 = {}
0x8268e948 = {}
0x8268dd48 = {}
0x825383b8 = {}
0x827d4320 = {}
0x826051f0 = {}
0x824985f8 = {} #Weed crash fix
0x8248dc60 = {} #Ruffian crash fix
0x82365f98 = {} #Accessory pinata select crash fix
0x82352120 = {} #Storing medicine in store building crash fix
0x825d13f8 = {} #Deliver Trap crash Fix
0x823331c8 = {} #Packing Eggs crash fix
